### ISSUE TITLE
[vcvrack] Library weirdness

### ISSUE THREAD

**Issue by mysterybear** [osam-cologne/archlinux-proaudio#109]
Hi,

If I use this package, I get this strange behaviour with the Library where these plugin providers think they always need to update when they do not:

![image](https://user-images.githubusercontent.com/50906986/184531919-5df8f4e4-28d0-439c-b1b5-8413ca98a81c.png)

If I check the plugins directory, these plugins exist and are the most up-to-date version.

If I use the Rack @ https://vcvrack.com/downloads/RackFree-2.1.2-lin.zip there is no issue

So it really must be an issue with this build, but very strange, any ideas?

**Comment by cbix** [comment]
This is because our patch allows installing system-wide plugins to /usr/lib/vcvrack/plugins but Library installs and updates go to your home folder ~/.Rack2.

We should eventually fix the patch to prefer the version in your home directory over the system-wide installed version, since it may confuse users.

I can look into this after my vacation but someone else may already go and bump the `_plugin_ver` and `pkgrel` as soon as upstream has a git tag for the new version.

**Comment by cbix** [comment]
@mysterybear the order of loading plugins is now changed in the patch. Thanks for the feedback.
