### ISSUE TITLE
installing protobuf (23.4-1) breaks dependency 'libprotobuf.so=32-64' required by ola

### ISSUE THREAD

**Issue by topas-rec** [osam-cologne/archlinux-proaudio#251]
Dear maintainer,

I get

```
:: installing protobuf (23.4-1) breaks dependency 'libprotobuf.so=32-64' required by ola
```

during `# pacman --sync --refresh --sysupgrade` and found a [similar issue in this repo a year ago](https://github.com/osam-cologne/archlinux-proaudio/pull/61). I don't understand what made the difference there except of a rebuild, but:

Can you fix the current issue in this repo, too?

**Comment by SpotlightKid** [comment]
Unfortunately the current ola release does not compile with the latest protobuf version:

https://github.com/OpenLightingProject/ola/issues/1867

We have to wait for a new, fixed ola release.

**Comment by topas-rec** [comment]
Thank you for the quick update.

**Comment by topas-rec** [comment]
Installing the current head version using [ola-git](https://aur.archlinux.org/packages/ola-git) worked successfully.

**Comment by SpotlightKid** [comment]
I tried to fix the configure script with the help of a patch posted in the linked issue, but it just fails one step later due to wrong compiler flags for the C++ standard level. I really have no idea how all this autoconf stuff works (normally I wouldn't touch autoconf with a stick), so I guess we have to wait until someone else figures this out.

**Comment by SpotlightKid** [comment]
I don't think this is fixed. CI still fails and package is not updated.

**Comment by cbix** [comment]
Sorry this took half a year, I was waiting for an upstream solution for too long :D
